[colors]
ansi = ["#161616", "#ef596f", "#89ca78", "#e5c07b", "#61afef", "#c678dd", "#60c0cc", "#abb2bf"]
background = "#161616"
brights = ["#222222", "#f96379", "#93d482", "#efca85", "#6bb9f9", "#df69e8", "#6fcfdb", "#b5bcc9"]
cursor_bg = "#abb2bf"
cursor_border = "#abb2bf"
cursor_fg = "#161616"
foreground = "#b5bcc9"
selection_bg = "#393939"

[colors.tab_bar]
background = "#161616"

[colors.tab_bar.active_tab]
bg_color = "#161616"
fg_color = "#abb2bf"
intensity = "Bold"
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#2d2d2d"
fg_color = "#abb2bf"
intensity = "Normal"
underline = "None"
